[build]
    command = "npm run build"
    publish = "dist"
    functions = "src/functions"
    NODE_ENV = "10.15.3"

[den]
    command = "npm run start"

[[redirects]]
    from = "/new"
    to = "/.netlify/functions/newInvite"
    status = 200